### ISSUE TITLE
set genre.count + medium.count on saves

### ISSUE THREAD

**Issue by eliataylor** [eliataylor/ampp-keystone#1]
Both models/Genre.js and models/Medium.js need a `count` field to store how many published Content items exist for each term.

Ideally, the number is not simply incrementing or reducing but being reset from an aggregate query, so that other imports outside of keystone will preserve the correct number on any save.

**Comment by r3wt** [comment]
@eliataylor 

I did it like this
```js
Content.schema.post('save',(doc,next)=>{
	//update count on Genre and Medium
	Promise.all([
		keystone.list('Genre').model.update({_id: doc.genre },{$inc: {count:1}}).exec(),
		keystone.list('Medium').model.update({ _id: doc.medium },{$inc: {count:1}}).exec()
	])
	.then(()=>next())
	.catch((err)=>{
		console.log('Content.schema.post.save update genre medium counts fails!');
		console.log(err);
		next();
	});
});
```
But i just realized the approach is naive.  Save middleware will be fired for all document instance functions, so this count would quickly become innacurate if we update any documents with instance methods.

**Comment by r3wt** [comment]
So, i will write a new version. first it will perform a count for each, then it will update the models.

**Comment by r3wt** [comment]
```js
Content.schema.post('save',(doc,next)=>{
	//update count on Genre and Medium

	let chain1 = keystone.list('Content').count({ genre: doc.genre }).exec()
	.then((err,num)=>{
		if(err){
			throw err;
		}
		return keystone.list('Genre').model.update({_id: doc.genre },{ count: num }).exec()
	});

	let chain2 = keystone.list('Content').count({ medium: doc.medium }).exec()
	.then((err,num)=>{
		if(err){
			throw err;
		}
		return keystone.list('Medium').model.update({_id: doc.medium },{ count: num }).exec()
	});

	Promise.all([
		chain1,
		chain2
	])
	.then(()=>next())
	.catch((err)=>{
		console.log('Content.schema.post.save update genre medium counts fails!');
		console.log(err);
		next();
	});
});
```
This is what i came up with. lmk what u think

**Comment by eliataylor** [comment]
again, i'm not really familiar with the keystone methods but this looks very good in general. 

can you commit it to the repo?

**Comment by eliataylor** [comment]
ah. sorry found it in the heroku repo
