### ISSUE TITLE
Genre and Mediums should be required but they are currently not

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#10]
Currently, you can upload your content without having the genre or medium selected. It'd be nice if this could be a requirement ( see attached
![2017-09-23_1542](https://user-images.githubusercontent.com/32228117/30777357-dcbc0738-a075-11e7-9322-25b820281847.png)
 screen capture).

Thanks!

**Comment by BisoMandic** [comment]
Changed this to a bug since filtering based on genre is a fairly pivotal part of the site.
Thanks!

**Comment by r3wt** [comment]
@eliataylor please review. just pushed to heroku a potential fix.

**Comment by eliataylor** [comment]
![screen shot 2017-09-27 at 6 46 42 pm](https://user-images.githubusercontent.com/6335974/30945631-3f94d6a0-a3b4-11e7-86e7-6c60c1cb52c7.png)
