### ISSUE TITLE
Order of Amppstar sections needs to be changed so that it matches the descriptions below

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#12]
The top AMPP sections are out of order and should be Art, Music, Poetry, and Photography. See attached screen capture.

![2017-09-23_1559](https://user-images.githubusercontent.com/32228117/30777498-acf78682-a078-11e7-8682-20f3260ca665.png)

**Comment by r3wt** [comment]
this can be closed. just pushed the following fix to `heroku/master`
```js
var mediumOrder = ['art','music','poetry','photography'];
mediums.sort(function(a, b){
    return mediumOrder.indexOf(a.slug) - mediumOrder.indexOf(b.slug)
});
```

**Comment by BisoMandic** [comment]
Thanks Ken!
