### ISSUE TITLE
Border around the different mediums and a small shift down.

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#13]
It would be nice if the 4 sections, Art, Music, Poetry, and Photography had a thick border around them so that the pictures pop and could be moved down a bit so they were more centered on the page.

Thanks!

**Comment by eliataylor** [comment]
i updated the page CSS to center all blocks vertically and horizontally, whether the sidebar is open or closed.

i'll play around with border ideas next

**Comment by eliataylor** [comment]
i added slightly rounded corners the a box-shadow: 4px 4px 5px #2b2b2b;

![screen shot 2017-09-27 at 6 44 49 pm](https://user-images.githubusercontent.com/6335974/30945588-01ac3b9e-a3b4-11e7-8b46-d6efc17680c1.png)
