### ISSUE TITLE
Content description overlaps with author's name

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#15]
When writing a description for a medium, the description shows up on the main page and overlaps the author's name. It's best to keep the description on the individual photograph/medium's page, see screenshots below:

![2017-09-24_0731](https://user-images.githubusercontent.com/32228117/30783140-5b389038-a0fb-11e7-8a05-ef6125d81fb0.png)
![2017-09-24_0738](https://user-images.githubusercontent.com/32228117/30783153-73b6e5f6-a0fb-11e7-867d-f8d5e34b69cd.png)

**Comment by eliataylor** [comment]
For practical purposes now, I'm just removing the Description field from the dashboard cells. 

Change this to the Enhancement tag if you want to put it back. (To make this wrap nicer, we might need to strip HTML like the line breaks and white space you included from the Keystone admin access. User forms don't support html yet. Let me know your desire rules for whether to show it or not here, and whether to strip extra whitespace, any formatting, and/or grow the cell to fit more/all of the content?
