### ISSUE TITLE
Improve My Profile updating

### ISSUE THREAD

**Issue by eliataylor** [eliataylor/ampp-keystone#18]
1. validate email changes do not conflict with other users
2. pre-select the user's existing Mediums when the form loads
3. do not overwrite the user's image unless specifically requested to change or delete it.

**Comment by r3wt** [comment]
On it

**Comment by r3wt** [comment]
1. check 

![image](https://user-images.githubusercontent.com/4483325/31557514-ae3e3554-b00e-11e7-95ca-518c8d8c6d8a.png)

also note here, i split up name.first and name.last i will apply same fix for registration. the name in the above image should shed light on my reasoning. 

Names like "Justin Van Zant" or whatever wouldn't be possible. cool?

**Comment by r3wt** [comment]
2. check

simple fix really
```html
<select multiple class="form-control" name="medium[]" id="join-medium">
    {% for link in mediums %}
        <option value="{{link._id}}"
            {% if link._id in form.medium %} selected="selected"{% endif %}
            >{{link.profession}}</option>
    {% endfor %}
</select>
```

use `var in array` syntax to check for presence in array. use `var in array|keys` to check for var in object keys`

**Comment by r3wt** [comment]
@eliataylor I pushed these changes to heroku master. i tried to pull master from here and commit to master here but i get access denied message in git. please advise.

![image](https://user-images.githubusercontent.com/4483325/31558515-c1581a34-b012-11e7-8b62-7c5793e7909c.png)

**Comment by eliataylor** [comment]
send me your ssh key.

**Comment by r3wt** [comment]
alright eli, i committed to the repo now. i am having trouble reproducing the issue with profiles. it seems to always reject my profile image. please advise on steps to reproduce failure.

**Comment by eliataylor** [comment]
it seems the issue was missing enctype="multipart/form-data"

**Comment by eliataylor** [comment]
(additionally, it turns out the input name needs to be [field]_upload in order to be processed automatically)

**Comment by eliataylor** [comment]
https://github.com/eliataylor/ampp-keystone/blob/master/templates/views/forms/join.twig#L85
