### ISSUE TITLE
'About' page

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#19]
I think that having an 'About' page before the Sign-up option would be a good idea so those who do not really know what the site is about, can get a better idea. I was thinking that perhaps we can just take what I wrote on the FB page:

> Ever wanted a site a where you can share your Artistic, Musical, Photographic and Poetic talent with everyone? Well, Amppstar.com might be just the one!
> 
> A site that gets you noticed and helps you find talent for your event, on Amppstar.com you'll definitely find great content!
> 
> So Sign-up, Share, Like and most importantly get your content out, because that's what Amppstar.com is all about!

**Comment by eliataylor** [comment]
go to https://afternoon-mesa-52732.herokuapp.com/about
