### ISSUE TITLE
Link to Facebook and Instagram pages

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#23]
It would be nice if the Facebook and Instagram logos lead to the actual pages:

![2017-10-24_2108](https://user-images.githubusercontent.com/32228117/31978647-99982e62-b8ff-11e7-90ec-f42d0ff08f56.png)

The link to the pages are here:
https://www.facebook.com/amppstar/
https://www.instagram.com/amppstar_ig/

**Comment by eliataylor** [comment]
added.
