### ISSUE TITLE
Unable to delete and edit profile picture

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#24]
Once a profile picture is selected, it does not appear that you can remove it. You can replace it with another picture, but the option to delete the picture isn't available.

![2017-10-24_2125](https://user-images.githubusercontent.com/32228117/31979101-27e4e79e-b902-11e7-9ddf-d3dc8e519c8d.png)

**Comment by BisoMandic** [comment]
Changing out the image also seems to be causing an issue:
![2017-10-24_2142](https://user-images.githubusercontent.com/32228117/31979499-49c28360-b904-11e7-96a8-68598dbd7343.png)

**Comment by eliataylor** [comment]
the image upload is now fixed

(for reference, https://github.com/eliataylor/ampp-keystone/blob/master/templates/views/forms/content.twig#L64)

**Comment by eliataylor** [comment]
done
