### ISSUE TITLE
Copyright on the content page

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#25]
![2017-10-25_2007](https://user-images.githubusercontent.com/32228117/32031739-3cd5d46a-b9c0-11e7-8e21-dda1d608eca7.png)

**Comment by eliataylor** [comment]
the copyright rests above the bottom right of every full width image. on mobile (smaller) screens this is always the case, but some larger screens with taller / narrower images, the copyright falls outside of the image at the bottom left of that image's region.

**Comment by eliataylor** [comment]
the easiest solution is to position the copyright on the bottom left instead of the bottom right. is that ok?

**Comment by BisoMandic** [comment]
Yup, that's fine!

**Comment by eliataylor** [comment]
done

**Comment by eliataylor** [comment]
![screen shot 2017-10-26 at 9 24 21 pm](https://user-images.githubusercontent.com/6335974/32087899-12bc2cf4-ba94-11e7-9673-1c428d8a62cd.png)
