### ISSUE TITLE
Entire medium picture should take you to the Art/Music/Poetry/Photo page

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#27]
We noticed that in order to go to the medium page, you must click on the upper part of the medium picture/the writing section for the arrow to change to a hand allowing you to go the desired page. It would be good if the entire picture took you to that page. 

*I did a video showing what I mean but GIT doesn't allow that type here. A picture doesn't capture the arrow and hand when screen captured. If you want an example, let me know.

**Comment by eliataylor** [comment]
fixed
