### ISSUE TITLE
Newest content should show up first

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#28]
The newest posted content should be first whereas currently, it shows up in random parts of the medium page. It also does not appear to get filtered by alphabetical order either.

![2017-10-28_1414](https://user-images.githubusercontent.com/32228117/32138107-96c1d5d8-bbea-11e7-81ee-2fcb8899e58b.png)

**Comment by eliataylor** [comment]
now sorting by `sort({medium:1, createdAt:1})` (medium, then creation date).

**Comment by eliataylor** [comment]
if you'd prefer just creation or publish date, just let me know
