### ISSUE TITLE
Remove option to download music!!!!

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#29]
Cody made a great point that there shouldn't be an option to download the music locally. He noted that musicians should decide whether to share this on their own websites if they want. Having this available on Amppstar means website users would be getting this new music for free and could potentially steal it/would be discouraged from supporting the musician.

**Comment by eliataylor** [comment]
i can remove the clickable option to download the music from within the player...

but this won't protect the mp3 from downloads directly, should a user be savy enough to find the MP3 url

**Comment by eliataylor** [comment]
https://stackoverflow.com/questions/41115801/in-chrome-55-prevent-showing-download-button-for-html-5-video (fastest solution)

**Comment by eliataylor** [comment]
works in chrome

**Comment by eliataylor** [comment]
also works in safari
