### ISSUE TITLE
create Medium dashboard filters / api / result sets

### ISSUE THREAD

**Issue by eliataylor** [eliataylor/ampp-keystone#3]
Please extend routes/views/dashboard.js so that it can return HTML or JSON of published content by medium and/or genres, using this URL:

/search/:medium?genres=[]

Json structure response should look like this:

```
{
section:"Dashboard",
filters : {
 medium:String|ID,
 genres: Array[id,name,icon,count of matching content items by current selected medium ]
}
data: [[pagination array](http://keystonejs.com/docs/database/#lists-paginate)]
}
```

and HTML should just render a simple template of blocks. No styling or functional javascript is necessary yet. Below are the designs just to describe the filters.

![02_dashboard_poetry](https://user-images.githubusercontent.com/6335974/30089108-9f79f138-925f-11e7-9c6e-aa000e4fb99b.jpg)

**Comment by r3wt** [comment]
@eliataylor i created a new view and controller, both called dashboard2. additionally, i modified the content model, changing the field from `author` to `user`. i'm super ocd i like to keep the naming of ref fields consistent with the model name.

**Comment by eliataylor** [comment]
sounds good!

but i don't see the commit in heroku or here.

**Comment by r3wt** [comment]
@eliataylor i just added it
