### ISSUE TITLE
Botton of poetry needs copyright

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#30]
I was noticing yesterday that all other mediums except the poetry one have the user's copyright info at the bottom of the page/on the pictures except the poetry one. This is also needed for this medium as well. This is important because I have been asked about this very thing by a poet friend recently.

![2017-10-28_1423](https://user-images.githubusercontent.com/32228117/32138178-a6202380-bbeb-11e7-9301-eb2b175befad.png)

**Comment by eliataylor** [comment]
fixed
