### ISSUE TITLE
Genre filter to reflect user's genres

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#32]
We noticed that 'Filter by genre" pulls up all the genres from Amppstar. It would be nice if this reflected only the user's genres so it's easier to find  exactly what you're looking for:

![2017-10-28_1429](https://user-images.githubusercontent.com/32228117/32138251-af7806f4-bbec-11e7-9ece-f6262344a77f.png)

**Comment by eliataylor** [comment]
this is easy to do, but requires users actually maintain their selected Mediums, alongside the content the upload.

**Comment by eliataylor** [comment]
mongoose query tags on content owned by author

**Comment by eliataylor** [comment]
done
