### ISSUE TITLE
Darker filtering colour

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#34]
The colour that appears (light grey) when you hover over a genre or medium to filter by is quite light. If this could be a darker grey or perhaps a blue, it would be easier to see, especially for people who have vision issues.

![2017-10-28_1437](https://user-images.githubusercontent.com/32228117/32138305-91eda17e-bbed-11e7-9e11-e0229f0e4a28.png)

**Comment by eliataylor** [comment]
i picked #63a4da. Otherwise, provide a color code. This tool can help: www.colorzilla.com/gradient-editor/
