### ISSUE TITLE
User sign-in takes user to edit profile page instead of their profile content page

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#37]
After a user signs-in, they should be taken to their profile content page rather than their 'Edit profile' page as that is more visually appealing.

E.g instead of seeing this first:

![2017-10-28_1501_001](https://user-images.githubusercontent.com/32228117/32138506-0b215916-bbf1-11e7-95a5-117850b2407a.png)

They should see this instead:

![2017-10-28_1501](https://user-images.githubusercontent.com/32228117/32138511-1c745db2-bbf1-11e7-8490-28c69f7340ae.png)

**Comment by eliataylor** [comment]
this is more visually appealing to you because you have a rich profile with content and your profile details filled out.

this page will usually be pretty empty when newer users signing.

**Comment by BisoMandic** [comment]
Hello Eli,
I agree. How about taking the user to the AMPP home page instead??

**Comment by eliataylor** [comment]
done
