### ISSUE TITLE
Setup Grunt or Webpack to streamline local development

### ISSUE THREAD

**Issue by eliataylor** [eliataylor/ampp-keystone#4]
I have a `grunt serve` command to lint, test, and run the project locally, however it is currently not showing console.log messages in the terminal. 

Please fix that or reconfigure the package.json and related config files to `watch` file changes and rebuild the server locally.

**Comment by r3wt** [comment]
working on this

**Comment by r3wt** [comment]
@eliataylor unable to continue because of error:

Warning: Task "node-inspector" not found. Use --force to continue.

**Comment by eliataylor** [comment]
@r3wt, "use --force to continue" . However, the problem here is that console.log statements do not show up in the terminal. 

i you cannot figure out a way to resolve this, just run `npm run dev-start` and test that way; and I can try to patch this bug.

**Comment by r3wt** [comment]
@eliataylor you can pull this change from heroku. i consider this matter resolved.
![image](https://user-images.githubusercontent.com/4483325/30222767-9d9bf20a-948d-11e7-85ba-fefa015e35bd.png)

**Comment by r3wt** [comment]
you can see how i did this in `grunt/express.js` task

add the following to the `options` object:
```
opts: {
	stdio: 'inherit'
}
```

![image](https://user-images.githubusercontent.com/4483325/30222843-ece53e66-948d-11e7-889d-ef4de80d8467.png)

**Comment by eliataylor** [comment]
yup. also seemed to help for me to just blow out node_modules and rerun `npm install`
