### ISSUE TITLE
Female gender does not update/display

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#41]
When I select my gender as 'Female' and update my profile, it does not hold and defaults me to the male picture if I don't have a picture uploaded. The male one appears to be working as expected.

![2017-10-28_1526](https://user-images.githubusercontent.com/32228117/32138699-a71cdf18-bbf4-11e7-8412-c83a35c9ec62.png)

![2017-10-28_1525](https://user-images.githubusercontent.com/32228117/32138702-ad427902-bbf4-11e7-8e54-dc8a365ed7db.png)

**Comment by eliataylor** [comment]
fixed. 

(was a typo in the form)
