### ISSUE TITLE
**Ability to align and style poetry before publishing and during editing

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#42]
Hello Eli,
I noticed that when I go to edit my poetry that you can see the HTML and not the styling. Also, new users don't seem to have the ability to style like I do with keystone e.g align, bold, italicize, underline their words. I think this is pretty important.

![2017-11-05_1035](https://user-images.githubusercontent.com/32228117/32417347-680070e8-c215-11e7-9336-da35dfa30a78.png)
![2017-11-05_1036](https://user-images.githubusercontent.com/32228117/32417348-6d83517a-c215-11e7-9076-9fd10e5716f8.png)
![2017-11-05_1036_001](https://user-images.githubusercontent.com/32228117/32417351-759eebf8-c215-11e7-90d8-45bcc2b26b1c.png)

**Comment by eliataylor** [comment]
requires TinyMCE or some other editor plugin

**Comment by BisoMandic** [comment]
OK, what does it take to add in such a plugin? Can it be done?

**Comment by eliataylor** [comment]
done.
