### ISSUE TITLE
**Ability to post music videos in the music section

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#43]
Hello Eli,
I was thinking about the music medium again and really think the ability to post videos i.e people playing on their guitar is very important. Many young people don't copyright or record their songs in a studio like Zoltan and Joe do so this is pretty important. Otherwise what would prevent them from just going to YouTube where anything goes.

**Comment by eliataylor** [comment]
done

**Comment by BisoMandic** [comment]
I have to re-open this one as it does not appear to be working as I first suspected.

**Comment by eliataylor** [comment]
repaired. (it seems i had broken the mp4 uploader when implementing a the Sharp image processor which doesn't handle videos).

uploading Videos the the Media input field on music works now. 

Videos will not work in other fields per design.

we should setup another Issue to handle the relatively ugly layout for these:

![testvideo](https://user-images.githubusercontent.com/6335974/33581970-d610610c-d907-11e7-9d1f-3da95cbe7e3b.png)
