### ISSUE TITLE
Amppstar's mobile main page looks jumbled

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#44]
Hello Eli,
I forgot to tell you last time that other than the main page, the mobile version of the site looks great! Attached is the image of what it looks like on my cell phone. What can be done to make it look neater? Can we remove the text and have two by side and two below?

![screenshot_20171105-105426](https://user-images.githubusercontent.com/32228117/32417533-5423af92-c218-11e7-9742-edb8722ad8ee.png)

**Comment by eliataylor** [comment]
fixed
