### ISSUE TITLE
Ampp Star Terms and Conditions

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#46]
Hello Eli,

Attached are the Terms and Condition. Please have a quick look to ensure I'm not missing anything. Did you say you wanted me to put it into Google+ as it's easier for formatting?

[Amppstar_T&C_english.docx](https://github.com/eliataylor/ampp-keystone/files/1464078/Amppstar_T.C_english.docx)

**Comment by eliataylor** [comment]
i put the document here: https://afternoon-mesa-52732.herokuapp.com/about/termsandconditions, but from where all do you want it linked again?

**Comment by eliataylor** [comment]
i put in in the footer.

**Comment by BisoMandic** [comment]
Hello Eli,

Sorry, I just saw your note, I must not have gotten the email notification on this one or somehow missed it. Is it possible to have this part of the registration process? I'd like for users to "Accept the terms" in order to be able to sign up for the site to ensure they have indeed read them.

Thanks!

B

**Comment by eliataylor** [comment]
closing this. and will open a new Issue for the Acceptance requirement
