### ISSUE TITLE
Mobile version side options go the bottom of the page

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#47]
Hello Eli,

I noticed that on the mobile version that the options to search/add content are at the bottom of the page to the point where you can't find them until you fully scroll down. Attached is a screen capture (on the app the options are actually further down). It'd be good if these were at the top so they're easy to see.

![screenshot_20171116-190315](https://user-images.githubusercontent.com/32228117/32926017-1ee4067c-cb02-11e7-8f6a-368c63cef8af.png)

**Comment by eliataylor** [comment]
i never saw this, but suspect it's fixed now with this last release
