### ISSUE TITLE
Medium pictures swap-out :)

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#48]
Howdy Eli,

As I mentioned during our chat, I'd like the current medium pictures to be swapped out with the following ones:

Art:

![2017-11-16_1956](https://user-images.githubusercontent.com/32228117/32927799-fd9c7cb0-cb0b-11e7-83df-218569996644.png)

Music

![2017-11-16_1949](https://user-images.githubusercontent.com/32228117/32927732-9844336c-cb0b-11e7-8465-26f8cf92d5ed.png)

Poetry:

![2017-11-16_1949_001](https://user-images.githubusercontent.com/32228117/32927738-a83f902c-cb0b-11e7-9e88-5eb6260a037e.png)

Photography

![photography](https://user-images.githubusercontent.com/32228117/32927721-7dbadc3a-cb0b-11e7-974f-c385835d3c72.png)

**Comment by eliataylor** [comment]
can you repost the middle two images without the captions or logo?

**Comment by eliataylor** [comment]
Ideally around 280 pixels width/height

**Comment by eliataylor** [comment]
done. (although i'll need to readdress the vertical alignment)


![screen shot 2017-11-23 at 10 18 08 pm](https://user-images.githubusercontent.com/6335974/33197765-3e8ca37c-d09c-11e7-9a60-198969fc445a.png)
