### ISSUE TITLE
Registration & My-Profile

### ISSUE THREAD

**Issue by eliataylor** [eliataylor/ampp-keystone#5]
the `/join` route currently works but needs backend support for optional `gender medium phone locale image` fields: https://github.com/eliataylor/ampp-keystone/blob/master/routes/views/join.js#L91

the `/my-profile` route currently is not implemented but ideally should leverage the same route as join, and identify the difference by the presence of a user _id parameter / query.

Both should validate input for obvious security hacks or user errors; whether with mongoose validation or whatever comes with keystoneJS.

**Comment by r3wt** [comment]
@eliataylor could you explain? i already added the optional fields to /join. not sure what you mean by the second part there.

**Comment by eliataylor** [comment]
We need another route to support User model changes for an existing user.

**Comment by eliataylor** [comment]
i was proposing that by `my-profile` and/or `my-profile/:action`

**Comment by r3wt** [comment]
Oh ok i gotcha

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by r3wt** [comment]
alright, i added the my profile route and edited myprofile.js you should be able to tweak to your liking.

**Comment by eliataylor** [comment]
i've made several changes to match the join.twig and myprofile.twig forms with a User model. 

unfortunately, while updating myprofile, i'm still getting an error: `Invalid path specified in fields to update [name.first name.last email phone gender medium locale website image] for list User`

**Comment by eliataylor** [comment]
(i did fix this error and added some precautions to not allow emptying the email / name / password fields).

**Comment by eliataylor** [comment]
i'm closing this to open an Enhancement for better profile updates > https://github.com/eliataylor/ampp-keystone/issues/18
