### ISSUE TITLE
Add ability to share on Instagram

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#7]

**Comment by BisoMandic** [comment]
Having the ability to share to Instagram would be great. Sharing on LinkedIn and Whatsapp is not necessary. Thanks!

**Comment by eliataylor** [comment]
i don't use instagram so didn't realize that it seems this isn't possible.

pretty sure they offer a sign-in feature though?

read more here: https://stackoverflow.com/questions/30542054/does-instagram-have-share-button-or-not
