### ISSUE TITLE
Small profile picture for the user

### ISSUE THREAD

**Issue by BisoMandic** [eliataylor/ampp-keystone#8]
Currently, when you upload a photograph for a user it does not show up when you click on their name in any of the mediums. It would be good to have this show-up or the male/female icon if they do not have a picture selected.

**Comment by eliataylor** [comment]
put some very simply styling in place. 

will close once zandro finishes the avitars per gender or in general.

**Comment by eliataylor** [comment]
![screen shot 2017-09-26 at 7 31 11 am](https://user-images.githubusercontent.com/6335974/30868547-d320c310-a293-11e7-8491-cf84821ea3e8.png)

**Comment by BisoMandic** [comment]
This looks great, Eli! The exact size of the picture I was thinking! :)
